steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform init"]
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform plan"]    
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform apply --auto-approve"]   

  # - id: 'tf destroy'
  #   name: 'hashicorp/terraform:1.0.0'
  #   entrypoint: sh
  #   args: ["-c","terraform -chdir=GCP/create-ha-vpn-comm plan -destroy -out=plan.out"]    
  # - id: 'tf destroy plan'
  #   name: 'hashicorp/terraform:1.0.0'
  #   entrypoint: sh
  #   args: ["-c","terraform -chdir=GCP/create-ha-vpn-comm apply plan.out"]    